// OIDC 퀘스트 — 시나리오 데이터
// step: { at: NPC id, lines: [[화자, 대사]...], choice?: { q, opts: [{ t, ok, fb }] },
//         after?: [[화자, 대사]...], give?: [아이템], take?: [아이템], goal: 다음 목표 문장, trap?: { at, lines } }
// 첫 step 의 goal 은 챕터 시작 시 보이는 목표, 각 step 의 goal 은 그 step 을 끝낸 뒤의 목표입니다.

window.ITEMS = {
  state:     { label: "state", color: "#e0a03a", desc: "CSRF 방지용 일회용 값. 콜백에서 짝을 맞춘다" },
  nonce:     { label: "nonce", color: "#c77dff", desc: "ID 토큰 재사용 방지용 일회용 값" },
  verifier:  { label: "verifier", color: "#ff6b6b", desc: "PKCE 비밀값. 백엔드만 안다" },
  challenge: { label: "challenge", color: "#ff9f9f", desc: "SHA256(verifier). 공개해도 되는 해시" },
  code:      { label: "code", color: "#4dabf7", desc: "인가 코드. 한 번만, 짧게 쓸 수 있다" },
  idtoken:   { label: "ID토큰", color: "#63e6be", desc: "OP 가 서명한 '이 사용자는 누구인가' 증명서" },
  verified:  { label: "검증됨", color: "#38d9a9", desc: "서명이 확인된 ID 토큰" },
  user7:     { label: "user 7", color: "#ffd43b", desc: "DB 에서 찾은 사용자" },
  session:   { label: "세션", color: "#a9e34b", desc: "Redis session:{sid}, 브라우저엔 HttpOnly 쿠키" },
  malLink:   { label: "수상한 링크", color: "#868e96", desc: "말로리가 뿌린 콜백 링크" },
  forged:    { label: "위조 토큰", color: "#fa5252", desc: "sub=admin 으로 고친 토큰" },
  noneTok:   { label: "alg:none", color: "#fa5252", desc: "서명이 비어 있는 토큰" },
  jkuTok:    { label: "jku 토큰", color: "#fa5252", desc: "키를 골목에서 받으라는 토큰" },
  newTok:    { label: "새 kid 토큰", color: "#63e6be", desc: "kid=key-2026-10 으로 서명된 토큰" },
};

window.NPCS = {
  jieun:  { name: "지은 (사용자)", x: 24, y: 21, kind: "person", color: "#f783ac", hair: "#5c3b28",
            idle: "포털 쓰고 싶은데… 뭘 해야 하는지는 당신이 알 거라 믿어요." },
  kim:    { name: "김담당 (사용자)", x: 17, y: 23, kind: "person", color: "#74c0fc", hair: "#222",
            idle: "저는 서버 42 담당이에요. 오늘은 별일 없네요." },
  console:{ name: "관제 콘솔 (백엔드)", x: 21, y: 11, kind: "terminal",
            idle: "대기 중. 들어온 요청이 없습니다." },
  redis:  { name: "레디스 금고지기", x: 32, y: 11, kind: "person", color: "#e03131", hair: "#fff",
            idle: "여긴 짧게 사는 것들만 맡는다. state, 세션, JWKS 캐시 같은 것." },
  db:     { name: "DB 서고 사서", x: 7, y: 12, kind: "person", color: "#2f9e44", hair: "#868e96",
            idle: "users, user_roles, server_owner… 오래 남는 기록은 다 여기 있죠." },
  op:     { name: "SSO 문지기 (OP)", x: 39, y: 10, kind: "person", color: "#5f3dc4", hair: "#ffd43b",
            idle: "비밀번호는 나만 본다. 너희 앱은 내가 서명한 토큰만 받으면 돼." },
  jwks:   { name: "JWKS 게시판 (jwks_uri)", x: 35, y: 10, kind: "board", color: "#5f3dc4",
            idle: "공개키 목록: key-2026-09 (RSA, RS256). 누구나 읽을 수 있습니다." },
  mallory:{ name: "말로리", x: 38, y: 25, kind: "hood",
            idle: "흐흐… 오늘은 그냥 구경만 하지." },
  fake:   { name: "골목 게시판", x: 42, y: 24, kind: "board", color: "#495057",
            idle: "누군가 공개키를 잔뜩 붙여 놨다. 출처는 적혀 있지 않다." },
};

window.CHAPTERS = [
  {
    id: "c1", title: "1장. 첫 로그인",
    intro: "지은이 회사 SSO 계정으로 포털에 로그인하려 합니다. Authorization Code + PKCE 흐름을 처음부터 끝까지 직접 걸어 봅시다.",
    start: "광장의 지은에게 말을 걸자",
    takeaways: [
      "state 는 '이 콜백이 내가 시작한 로그인인가', nonce 는 '이 토큰이 이번 로그인 것인가'를 확인한다",
      "PKCE: 브라우저로는 해시(challenge)만, 토큰 교환 때 서버가 원본(verifier)을 보낸다",
      "ID 토큰은 jwks_uri 의 공개키 중 kid 가 같은 키로 서명을 확인하고, iss·aud·exp·nonce 를 본다",
      "사용자는 email 이 아니라 iss + sub 로 찾는다",
      "토큰은 서버(Redis 세션)에 두고 브라우저엔 HttpOnly 쿠키로 sid 만 준다",
    ],
    steps: [
      { at: "jieun",
        lines: [["지은", "포털에 로그인하고 싶어요. 회사 SSO 계정으로요!"], ["나", "좋아요. 비밀번호는 SSO 에만 입력하시면 돼요. 로그인 요청부터 준비할게요."]],
        goal: "관제 콘솔로 가서 로그인 요청을 준비하자" },
      { at: "console",
        lines: [["관제 콘솔", "GET /login 수신. OIDC 로그인을 시작합니다."], ["관제 콘솔", "일회용 값 세 개 생성: state(CSRF 방지), nonce(토큰 재사용 방지), code_verifier(PKCE 비밀값)."]],
        choice: { q: "콜백이 돌아올 때까지 이 값들을 어디에 보관할까?", opts: [
          { t: "Redis 에 5분 TTL 로", ok: true, fb: "짧게 살고, 서버가 여러 대여도 같이 볼 수 있습니다." },
          { t: "이 서버의 메모리 HashMap 에", fb: "서버가 여러 대면 콜백이 다른 서버로 갈 수 있고, 재시작하면 사라집니다." },
          { t: "리다이렉트 URL 쿼리에 전부 붙여서", fb: "verifier 가 브라우저와 로그에 노출되면 PKCE 가 의미 없어집니다." },
        ]},
        give: ["state", "nonce", "verifier"],
        goal: "레디스 금고에 값을 맡기자" },
      { at: "redis",
        lines: [["레디스 금고지기", "무엇을 맡기러 왔나?"], ["나", "로그인 하나를 시작했어요. 콜백 때까지 보관해 주세요."]],
        choice: { q: "어떤 명령으로 저장할까?", opts: [
          { t: "SET oidc:{state} {nonce, verifier} EX 300", ok: true, fb: "5분 뒤 자동으로 지워져서, 중간에 포기한 로그인이 쌓이지 않습니다." },
          { t: "SET oidc:{state} {nonce, verifier}  (만료 없음)", fb: "로그인을 포기한 사람의 값이 영원히 쌓입니다." },
          { t: "HSET users:{state} ...", fb: "사용자 정보가 아니라 일회용 로그인 상태입니다. 키 이름부터 목적을 드러내세요." },
        ]},
        after: [["레디스 금고지기", "보관 완료. 찾을 땐 state 로 찾는다. 브라우저에는 state 와 challenge 만 들려 보내."]],
        take: ["nonce", "verifier"], give: ["challenge"],
        goal: "SSO 탑으로 가서 인가 요청을 보내자" },
      { at: "op",
        lines: [["SSO 문지기", "인가 요청인가. 무엇을 들고 왔는지 보여 줘."]],
        choice: { q: "GET /authorize 에 무엇을 실을까?", opts: [
          { t: "client_id, redirect_uri, scope=openid, state, nonce, code_challenge", ok: true, fb: "브라우저를 거치는 요청이라 공개돼도 괜찮은 값만 실었습니다." },
          { t: "위 값들 + code_verifier", fb: "verifier 는 백엔드만 알아야 하는 비밀입니다. 여기서 보내면 code 를 훔친 사람이 같이 가져갑니다." },
          { t: "위 값들 + client_secret", fb: "브라우저 주소창을 지나는 요청에 비밀키를 실으면 누구나 봅니다." },
        ]},
        after: [["SSO 문지기", "지은 님이 로그인과 동의를 마쳤다. 인가 코드를 발급해서 redirect_uri 로 돌려보내지. state 도 그대로 붙여서."]],
        take: ["challenge"], give: ["code"],
        goal: "콜백이 들어온다. 관제 콘솔로 돌아가자" },
      { at: "console",
        lines: [["관제 콘솔", "GET /callback?code=c-81f2&state=st-4a1d 수신."]],
        choice: { q: "가장 먼저 무엇을 할까?", opts: [
          { t: "Redis 에서 state 가 있는지 확인한다", ok: true, fb: "내가 시작한 로그인의 응답인지부터 봅니다." },
          { t: "바로 code 로 토큰을 교환한다", fb: "누가 시작한 로그인인지 모르는 채 진행하면 로그인 CSRF 에 당합니다." },
          { t: "DB 에서 사용자를 찾는다", fb: "아직 토큰도 없어서 누구인지 모릅니다." },
        ]},
        goal: "레디스 금고에서 state 를 확인하자" },
      { at: "redis",
        lines: [["레디스 금고지기", "state=st-4a1d 를 찾는다고?"]],
        choice: { q: "어떻게 꺼낼까?", opts: [
          { t: "GETDEL oidc:st-4a1d", ok: true, fb: "꺼내면서 지웁니다. 같은 콜백이 다시 오면 (nil) 이라 거절됩니다." },
          { t: "GET 한 뒤, 나중에 DEL", fb: "같은 콜백이 동시에 두 번 오면 둘 다 GET 에 성공할 수 있습니다." },
          { t: "GET 만 하고 남겨 둔다", fb: "같은 콜백 URL 을 몇 번이고 재사용할 수 있게 됩니다." },
        ]},
        after: [["레디스 금고지기", "있었다. 맡겨 둔 nonce 와 verifier 를 돌려주지. 이 state 는 이제 폐기다."]],
        take: ["state"], give: ["nonce", "verifier"],
        goal: "SSO 탑에서 code 를 토큰으로 교환하자" },
      { at: "op",
        lines: [["SSO 문지기", "토큰 교환인가. 이번엔 브라우저를 거치지 않는 서버 간 요청이군."]],
        choice: { q: "POST /token 에 무엇을 보낼까?", opts: [
          { t: "code + code_verifier + 클라이언트 인증", ok: true, fb: "OP 가 SHA256(verifier) 를 계산해 처음 받은 challenge 와 비교합니다. code 만 훔친 사람은 verifier 가 없어 교환할 수 없습니다." },
          { t: "code 만", fb: "code 를 가로챈 사람도 똑같이 교환할 수 있습니다. 그걸 막는 게 PKCE 입니다." },
          { t: "code + code_challenge", fb: "challenge 는 이미 공개된 값이라 아무것도 증명하지 못합니다." },
        ]},
        after: [["SSO 문지기", "일치한다. ID 토큰과 액세스 토큰을 내주지. ID 토큰 헤더는 {alg: RS256, kid: key-2026-09} 다."]],
        take: ["code", "verifier"], give: ["idtoken"],
        goal: "서명 공개키는 JWKS 게시판에 있다. 확인하러 가자" },
      { at: "jwks",
        lines: [["JWKS 게시판", "jwks_uri = https://sso.example.com/jwks"], ["JWKS 게시판", "keys: [ key-2026-08 (RSA, RS256), key-2026-09 (RSA, RS256) ]"], ["나", "토큰 헤더의 kid 는 key-2026-09 였지."]],
        choice: { q: "어느 키로 서명을 검증할까?", opts: [
          { t: "kid 가 같은 key-2026-09", ok: true, fb: "n, e 로 공개키를 만들어 header.payload 의 서명을 확인했습니다. 결과: 일치." },
          { t: "더 오래 쓴 key-2026-08", fb: "kid 가 다르면 다른 개인키로 서명된 것이라 검증이 실패합니다." },
          { t: "통과할 때까지 모든 키를 하나씩", fb: "kid 매칭을 버리는 습관은 위험합니다. 키가 섞이면 엉뚱한 키로 통과할 여지가 생깁니다." },
        ]},
        take: ["idtoken"], give: ["verified"],
        goal: "관제 콘솔에서 토큰 내용을 확인하자" },
      { at: "console",
        lines: [["관제 콘솔", "payload: { iss: sso.example.com, aud: infra-portal, sub: u-1001, exp: 5분 뒤, nonce: n-7f3a, email: jieun@example.com }"]],
        choice: { q: "서명 다음으로 꼭 확인할 것은?", opts: [
          { t: "iss, aud, exp, nonce 전부", ok: true, fb: "발급자, 받는 앱, 만료, 이번 로그인과의 짝까지 모두 맞습니다." },
          { t: "exp 만", fb: "다른 앱용 토큰(aud)이나 다른 로그인에서 가로챈 토큰(nonce)을 막지 못합니다." },
          { t: "email 형식이 올바른지", fb: "email 은 식별자가 아닙니다. 형식 검사는 보안 검증이 아닙니다." },
        ]},
        after: [["관제 콘솔", "토큰의 nonce 가 Redis 에서 꺼낸 n-7f3a 와 같습니다. nonce 도 할 일을 다 했습니다."]],
        take: ["nonce"],
        goal: "DB 서고에서 사용자를 찾자" },
      { at: "db",
        lines: [["DB 서고 사서", "사용자를 찾는다고요? 무엇으로 찾을까요?"]],
        choice: { q: "어떤 값으로 사용자를 찾을까?", opts: [
          { t: "iss + sub", ok: true, fb: "sub 는 OP 안에서 바뀌지 않는 고유 ID 입니다. iss 와 묶으면 OP 를 여럿 붙여도 겹치지 않습니다." },
          { t: "email", fb: "email 은 바뀌거나 재사용될 수 있습니다. 퇴사자 주소를 새 사람이 받으면 남의 계정에 들어갑니다." },
          { t: "이름", fb: "동명이인이 있습니다." },
        ]},
        after: [["DB 서고 사서", "users id=7, sub=u-1001, 역할 ROLE_USER. 처음이면 여기서 가입 처리도 하죠."]],
        take: ["verified"], give: ["user7"],
        goal: "레디스 금고에 세션을 만들자" },
      { at: "redis",
        lines: [["레디스 금고지기", "이제 이 사용자를 기억해 둘 차례로군."]],
        choice: { q: "로그인 상태를 어떻게 유지할까?", opts: [
          { t: "SET session:{랜덤 sid} {userId=7, roles} EX 1800, 브라우저엔 HttpOnly 쿠키로 sid 만", ok: true, fb: "토큰은 서버에 두고, 브라우저 스크립트는 쿠키를 읽을 수 없습니다. 로그아웃은 DEL 한 줄입니다." },
          { t: "ID 토큰을 브라우저 localStorage 에", fb: "XSS 한 번이면 토큰이 통째로 빠져나갑니다." },
          { t: "쿠키에 userId=7 을 그대로", fb: "사용자가 쿠키를 8 로 고치면 남이 됩니다." },
        ]},
        take: ["user7"], give: ["session"],
        goal: "지은에게 로그인이 끝났다고 알리자" },
      { at: "jieun",
        lines: [["지은", "들어가졌어요! 그런데 포털에는 비밀번호를 한 번도 안 줬네요?"], ["나", "비밀번호는 SSO 만 봤어요. 우리는 SSO 가 서명한 ID 토큰으로 지은 님인 걸 확인했고요."]],
        goal: "" },
    ],
  },
  {
    id: "c2", title: "2장. 말로리의 골목",
    intro: "남동쪽 골목에 말로리가 나타났습니다. 진짜처럼 보이는 링크와 토큰을 들고 옵니다. 하나도 통과시키지 마세요.",
    start: "지은이 이상한 링크를 받았다고 한다. 광장으로 가자",
    takeaways: [
      "Redis 에 없는 state 의 콜백은 거절한다 (로그인 CSRF)",
      "JWT 는 암호화가 아니라 서명이다. payload 는 누구나 고칠 수 있고 서명이 그걸 잡는다",
      "alg 는 토큰이 아니라 서버 설정(허용 목록)이 정한다. none, HS256 혼동을 막는다",
      "공개키는 미리 정한 issuer 의 jwks_uri 에서만 받는다. 토큰의 jku 는 따르지 않는다",
    ],
    steps: [
      { at: "jieun",
        lines: [["지은", "메신저로 '포털 로그인 링크'를 받았어요. /callback?code=c-mal&state=st-mal … 눌러도 되나요?"], ["나", "잠깐만요. 저 state 를 우리가 만든 적이 있는지 볼게요."]],
        give: ["malLink"],
        goal: "레디스 금고에서 state 를 확인하자" },
      { at: "redis",
        lines: [["레디스 금고지기", "GETDEL oidc:st-mal → (nil). 그런 건 맡은 적 없다."]],
        choice: { q: "이 콜백을 어떻게 처리할까?", opts: [
          { t: "400 으로 거절한다", ok: true, fb: "우리가 시작하지 않은 로그인입니다. 말로리가 자기 계정으로 받은 code 를 지은의 브라우저에 밀어 넣는 로그인 CSRF 입니다." },
          { t: "code 는 진짜일 테니 진행한다", fb: "지은이 말로리 계정으로 로그인됩니다. 지은이 올리는 자료가 말로리 계정에 쌓입니다." },
          { t: "새 state 를 만들어 끼워 넣고 진행한다", fb: "검증을 우회하는 것과 같습니다." },
        ]},
        take: ["malLink"],
        goal: "골목의 말로리를 찾아가 보자" },
      { at: "mallory",
        lines: [["말로리", "쳇, state 를 보는군. 그럼 이건 어때? 진짜 ID 토큰에서 sub 만 admin 으로 살짝 고쳤지."]],
        give: ["forged"],
        goal: "JWKS 게시판의 공개키로 서명을 확인하자" },
      { at: "jwks",
        lines: [["JWKS 게시판", "key-2026-09 로 header.payload 서명 확인 → false"]],
        choice: { q: "어떻게 판단할까?", opts: [
          { t: "401. 서명 불일치", ok: true, fb: "서명은 원래 payload 에 대해 만들어진 것입니다. 한 글자만 바꿔도 맞지 않습니다." },
          { t: "payload 가 잘 읽히니 진짜다", fb: "JWT payload 는 Base64 일 뿐이라 누구나 읽고 고칠 수 있습니다." },
          { t: "sub 만 원래대로 돌려서 받아 준다", fb: "위조된 토큰을 고쳐서 쓰면 안 됩니다. 버립니다." },
        ]},
        take: ["forged"],
        goal: "말로리에게 돌아가자" },
      { at: "mallory",
        lines: [["말로리", "그럼 서명 자체를 없애지. 헤더에 alg: none. 서명 칸은 비워 뒀어."]],
        give: ["noneTok"],
        goal: "관제 콘솔에서 판정하자" },
      { at: "console",
        lines: [["관제 콘솔", "ID 토큰 헤더 { alg: none }, 서명 부분 비어 있음."]],
        choice: { q: "어떻게 처리할까?", opts: [
          { t: "허용 목록(RS256)에 없으니 바로 거절", ok: true, fb: "토큰이 스스로 말하는 alg 를 믿지 않습니다. 허용 목록은 서버 설정입니다." },
          { t: "alg 가 none 이니 서명 검사를 건너뛴다", fb: "옛 라이브러리들이 실제로 이렇게 뚫렸습니다." },
          { t: "HS256 으로 보고 공개키를 비밀키처럼 써서 검증", fb: "알고리즘 혼동 공격입니다. 공개키는 누구나 알기 때문에 누구나 그 '비밀키'로 서명할 수 있습니다." },
        ]},
        take: ["noneTok"],
        goal: "말로리에게 돌아가자" },
      { at: "mallory",
        lines: [["말로리", "마지막이다. 헤더에 jku 를 적어 뒀지. '공개키는 골목 게시판에서 받아라.' 내 키로 서명했으니 내 게시판 키로 보면 딱 맞을걸?"]],
        give: ["jkuTok"],
        goal: "어느 게시판의 키를 믿어야 할까?",
        trap: { at: "fake", lines: [["골목 게시판", "kid=evil-1 공개키. 이 키로 검증하면… 일치!"], ["나", "아차. 말로리가 서명하고 말로리 키로 검증했으니 맞을 수밖에. 공개키는 우리가 믿는 issuer 의 jwks_uri 에서만 받아야 한다."]] } },
      { at: "jwks",
        lines: [["JWKS 게시판", "kid=evil-1 은 목록에 없습니다. jwks_uri 를 한 번 다시 받아도 없습니다."]],
        choice: { q: "판정은?", opts: [
          { t: "401. 신뢰하는 키 목록에 없는 kid", ok: true, fb: "키 출처는 우리가 정합니다. 토큰이 가리키는 jku, x5u 는 따르지 않습니다." },
          { t: "jku 주소에서 키를 받아 검증한다", fb: "공격자가 서명하고 공격자 키로 검증받는 셈입니다." },
        ]},
        take: ["jkuTok"],
        goal: "말로리에게 결과를 알려 주자" },
      { at: "mallory",
        lines: [["말로리", "…철벽이군. 오늘은 물러가지."], ["나", "state, 서명, alg 허용 목록, 키 출처. 네 겹이면 충분하지."]],
        goal: "" },
    ],
  },
  {
    id: "c3", title: "3장. 키 교체의 날",
    intro: "SSO 가 서명 키를 교체합니다. 대응을 잘못하면 회사 전원이 로그인하지 못합니다.",
    start: "SSO 문지기가 공지가 있다고 한다. SSO 탑으로 가자",
    takeaways: [
      "OP 는 교체 기간에 옛 키와 새 키를 함께 공개한다",
      "JWKS 는 캐시하고, 모르는 kid 가 오면 그때 한 번 다시 받는다",
      "재조회는 횟수를 제한한다. 가짜 kid 로 OP 를 두드리는 걸 막는다",
    ],
    steps: [
      { at: "op",
        lines: [["SSO 문지기", "공지다. 오늘부터 key-2026-10 으로 서명한다. 당분간 옛 키와 새 키를 함께 게시판에 걸어 둔다."]],
        goal: "지은이 로그인 에러가 난다고 한다. 광장으로 가자" },
      { at: "jieun",
        lines: [["지은", "방금 로그인했는데 에러 페이지가 떴어요!"]],
        give: ["newTok"],
        goal: "관제 콘솔에서 원인을 보자" },
      { at: "console",
        lines: [["관제 콘솔", "ID 토큰 kid = key-2026-10"], ["관제 콘솔", "Redis JWKS 캐시 = [ key-2026-08, key-2026-09 ]  → 캐시에 없음"]],
        choice: { q: "어떻게 할까?", opts: [
          { t: "jwks_uri 를 한 번 다시 받아 본다", ok: true, fb: "모르는 kid 는 키 교체의 신호일 수 있습니다." },
          { t: "모르는 kid 니까 바로 401", fb: "키 교체 때마다 전원이 로그인하지 못합니다." },
          { t: "앞으로 캐시를 끄고 매 요청마다 JWKS 를 받는다", fb: "로그인마다 OP 를 호출하면 느려지고 OP 에 부하가 갑니다." },
        ]},
        goal: "JWKS 게시판에서 새 목록을 받자" },
      { at: "jwks",
        lines: [["JWKS 게시판", "keys: [ key-2026-09, key-2026-10 ]  (key-2026-08 은 내려감)"]],
        choice: { q: "이제 어떻게 할까?", opts: [
          { t: "캐시를 새 목록으로 바꾸고 key-2026-10 으로 검증", ok: true, fb: "서명 일치. 지은의 로그인이 통과합니다." },
          { t: "익숙한 key-2026-09 로 검증", fb: "kid 가 다르니 실패합니다." },
        ]},
        take: ["newTok"],
        goal: "레디스 금고에서 캐시 정책을 정하자" },
      { at: "redis",
        lines: [["레디스 금고지기", "JWKS 캐시를 갱신하겠다. 얼마나 들고 있을까?"]],
        choice: { q: "캐시 정책은?", opts: [
          { t: "응답의 Cache-Control max-age 를 따르고, 모르는 kid 재조회는 분당 1회로 제한", ok: true, fb: "Google 은 약 5.6시간이었습니다. 재조회 제한은 가짜 kid 토큰 폭탄을 막습니다." },
          { t: "만료 없이 영구 보관", fb: "폐기된 키를 계속 믿게 됩니다." },
          { t: "1초", fb: "사실상 캐시가 없는 것과 같습니다." },
        ]},
        goal: "지은에게 알려 주자" },
      { at: "jieun",
        lines: [["지은", "다시 되네요! 뭐가 문제였어요?"], ["나", "SSO 가 도장을 바꿨는데 우리가 옛 도장 목록만 들고 있었어요. 모르는 도장이 오면 목록을 한 번 새로 받게 했어요."]],
        goal: "" },
    ],
  },
  {
    id: "c4", title: "4장. 누구냐, 무엇을 하냐",
    intro: "로그인은 됐는데 '안 돼요' 문의가 들어옵니다. 401 과 403, 인증과 인가를 구분해 봅시다.",
    start: "지은이 서버 설정을 못 바꾼다고 한다. 광장으로 가자",
    takeaways: [
      "401: 누구인지 모른다 (인증 실패, 세션 없음)",
      "403: 누군지는 알지만 권한이 없다 (인가 실패)",
      "OIDC 는 인증까지. 무엇을 할 수 있는지는 우리 DB 의 역할과 소유권이 정한다",
      "세션 방식은 Redis DEL 한 줄로 즉시 로그아웃된다",
    ],
    steps: [
      { at: "jieun",
        lines: [["지은", "서버 42 설정을 바꾸려는데 거절당했어요. PUT /servers/42"]],
        goal: "레디스 금고에서 세션부터 확인하자" },
      { at: "redis",
        lines: [["레디스 금고지기", "GET session:s-91 → { userId: 7, roles: [ROLE_USER] }"]],
        choice: { q: "지금까지 알게 된 것은?", opts: [
          { t: "user 7 로 인증된 사용자다", ok: true, fb: "누구인지는 확인됐습니다. 다음은 이 사람이 서버 42 를 바꿔도 되는지입니다." },
          { t: "인증 실패다", fb: "세션이 있으니 누구인지는 압니다." },
        ]},
        goal: "DB 서고에서 서버 42 담당자를 확인하자" },
      { at: "db",
        lines: [["DB 서고 사서", "server_owner: server 42 → user 8 (김담당)"]],
        choice: { q: "지은(user 7)의 요청에 무엇을 돌려줄까?", opts: [
          { t: "403 Forbidden", ok: true, fb: "누군지는 알지만 이 서버에 대한 권한이 없습니다." },
          { t: "401 Unauthorized", fb: "401 은 누구인지 모를 때입니다. 지은은 이미 인증됐습니다." },
          { t: "200 으로 처리", fb: "남의 서버 설정이 바뀌었습니다. 로그인했다고 모든 걸 할 수 있는 건 아닙니다." },
        ]},
        goal: "김담당도 문의가 있다고 한다. 광장으로 가자" },
      { at: "kim",
        lines: [["김담당", "10분 전에 로그아웃했는데, 안 닫은 탭에서 GET /servers/42 요청이 나갔대요."]],
        goal: "레디스 금고에서 그 쿠키의 세션을 보자" },
      { at: "redis",
        lines: [["레디스 금고지기", "GET session:s-77 → (nil). 로그아웃 때 DEL 됐다."]],
        choice: { q: "그 요청에 무엇을 돌려줄까?", opts: [
          { t: "401", ok: true, fb: "쿠키는 남아 있어도 가리키는 세션이 없으니 누구인지 모릅니다." },
          { t: "403", fb: "403 은 누군지 알 때 씁니다. 지금은 누구인지조차 모릅니다." },
          { t: "200. 쿠키가 있으니까", fb: "로그아웃한 사람의 요청이 처리됩니다." },
        ]},
        goal: "지은에게 정리해 주자" },
      { at: "jieun",
        lines: [["지은", "그럼 OIDC 로 로그인하면 권한까지 정해지는 거예요?"]],
        choice: { q: "어떻게 설명할까?", opts: [
          { t: "OIDC 는 '누구인가'까지예요. '무엇을 할 수 있나'는 우리 DB 의 역할과 소유권으로 정해요", ok: true, fb: "인증은 SSO 에 맡기고, 인가는 우리 서비스가 책임집니다." },
          { t: "ID 토큰에 권한이 다 들어 있어요", fb: "ID 토큰은 신원 증명서입니다. 서비스별 권한은 그 서비스가 관리합니다." },
        ]},
        after: [["지은", "아하, 출입증은 SSO 가, 어느 방에 들어갈지는 포털이 정하는 거네요."]],
        goal: "" },
    ],
  },
];
